// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwycTRcKjhAd9IPfRNjbhBCqNaOd2MRRw',
    appId: '1:132150881340:web:9b5ac4904ccc706813e739',
    messagingSenderId: '132150881340',
    projectId: 'educationdummy-6c019',
    authDomain: 'educationdummy-6c019.firebaseapp.com',
    databaseURL: 'https://educationdummy-6c019-default-rtdb.firebaseio.com',
    storageBucket: 'educationdummy-6c019.firebasestorage.app',
    measurementId: 'G-LL4L1HJY9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCOSin5HMdJBe1lxpyZmOT9TM9b5c_zI',
    appId: '1:132150881340:android:cdfb1441eb65df2e13e739',
    messagingSenderId: '132150881340',
    projectId: 'educationdummy-6c019',
    databaseURL: 'https://educationdummy-6c019-default-rtdb.firebaseio.com',
    storageBucket: 'educationdummy-6c019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPiX-4R6kdfuBeLoKm8aO6vq3A1Ec_E2A',
    appId: '1:132150881340:ios:7e7cb5a55208bbb813e739',
    messagingSenderId: '132150881340',
    projectId: 'educationdummy-6c019',
    databaseURL: 'https://educationdummy-6c019-default-rtdb.firebaseio.com',
    storageBucket: 'educationdummy-6c019.firebasestorage.app',
    iosClientId: '132150881340-f9ogkhrkmv8l9qm6cqccptajjg11qth9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPiX-4R6kdfuBeLoKm8aO6vq3A1Ec_E2A',
    appId: '1:132150881340:ios:7e7cb5a55208bbb813e739',
    messagingSenderId: '132150881340',
    projectId: 'educationdummy-6c019',
    databaseURL: 'https://educationdummy-6c019-default-rtdb.firebaseio.com',
    storageBucket: 'educationdummy-6c019.firebasestorage.app',
    iosClientId: '132150881340-f9ogkhrkmv8l9qm6cqccptajjg11qth9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwycTRcKjhAd9IPfRNjbhBCqNaOd2MRRw',
    appId: '1:132150881340:web:99db114b0c6aebe813e739',
    messagingSenderId: '132150881340',
    projectId: 'educationdummy-6c019',
    authDomain: 'educationdummy-6c019.firebaseapp.com',
    databaseURL: 'https://educationdummy-6c019-default-rtdb.firebaseio.com',
    storageBucket: 'educationdummy-6c019.firebasestorage.app',
    measurementId: 'G-F4D4KT7ZJ8',
  );
}
